name: Publish new release of resume
on:
  push:
    tags:
      - "v*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: cv.tex
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: cv.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pings repo
        uses: ./ping-repo
        env:
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}
          REPO: shahdloo/shahdloo.github.io
