name: Publish new release of cv
on:
  push:
    paths:
      - "*.tex"
      - "*.bib"
    tags:
      - "v*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Compile LaTeX document
        uses: shahdloo/latex-action@master
        with:
          root_file: cv.tex
          latexmk_use_xelatex: true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cv.pdf
            library.bib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@main
        with:
          token: ${{ secrets.SECRET_CV }}
          repository: shahdloo/shahdloo.github.io
          event-type: update_cv
#       - name: Pings repo
#         uses: ./ping-repo
#         env:
#            GITHUB_TOKEN: ${{ secrets.SECRET_CV }}
#           REPO: shahdloo/shahdloo.github.io   
    
